language: generic

compiler:
    - gcc

os:
    - linux

dist:
    - xenial

addons:
    apt:
        packages:
        - sdcc
        - netpbm
        - cpmtools
        - lua5.1
        - lua-posix
        - ninja-build

script:
    - make

