language: generic

compiler:
    - gcc

os:
    - linux

dist:
    - xenial

addons:
    apt:
        packages:
        - netpbm
        - cpmtools
        - lua5.1
        - lua-posix
        - ninja-build
        - libz80ex-dev

script:
    - (git clone --depth=1 https://github.com/davidgiven/ack.git && cd ack && make +ack-cpm && make install)
    - make

